apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-datadog-operator
  namespace: acm-policy
  annotations:
    policy.open-cluster-management.io/categories: DE.CM Security Continuous Monitoring
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: datadog-operator-ns
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-operators
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: datadog-operator-subscription
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: datadog-operator-certified-rhmp
                  namespace: openshift-operators
                  labels:
                    operators.coreos.com/datadog-operator-certified-rhmp.openshift-operators: ""  
                spec:
                  channel: alpha
                  installPlanApproval: Automatic
                  name: datadog-operator-certified-rhmp
                  source: redhat-marketplace
                  sourceNamespace: openshift-marketplace
                  startingCSV: datadog-operator.v0.7.2
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-datadog-operator
  namespace: acm-policy
placementRef:
  name: placement-policy-datadog-operator
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-datadog-operator
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-datadog-operator
  namespace: acm-policy
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: jfn
        operator: In
        values:
          - 'yes'