apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-datadog-operator
  namespace: acm-policy
  annotations:
    policy.open-cluster-management.io/categories: DE.CM Security Continuous Monitoring
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: datadog-operator-ns
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-operators
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: datadog-operator-subscription
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: datadog-operator-certified-rhmp
                  namespace: openshift-operators
                  labels:
                    operators.coreos.com/datadog-operator-certified-rhmp.openshift-operators: ""  
                spec:
                  channel: alpha
                  installPlanApproval: Automatic
                  name: datadog-operator-certified-rhmp
                  source: redhat-marketplace
                  sourceNamespace: openshift-marketplace
                  startingCSV: datadog-operator.v0.7.2
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: datadog-operator-agent
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: datadoghq.com/v1alpha1
                kind: DatadogAgent
                metadata:
                  name: datadog
                  namespace: openshift-operators
                spec:
                  agent:
                    config:
                      criSocket:
                        criSocketPath: /var/run/crio/crio.sock
                      kubelet:
                        tlsVerify: false
                      securityContext:
                        runAsUser: 0
                        seLinuxOptions:
                          level: s0
                          role: system_r
                          type: spc_t
                          user: system_u
                    rbac:
                      serviceAccountName: datadog-agent-scc
                    apm:
                      enabled: false
                    log:
                      enabled: false
                      logsConfigContainerCollectAll: false
                    process:
                      enabled: true
                      processCollection: false
                    security:
                      compliance:
                        enabled: false
                      runtime:
                        enabled: false
                    systemProbe:
                      bpfDebugEnabled: false
                  clusterAgent:
                    config:
                      admissionController:
                        enabled: false
                      externalMetrics:
                        enabled: false
                      clusterChecksEnabled: false
                    replicas: 2
                  clusterChecksRunner:
                    replicas: 2
                  credentials:
                    apiKey: <API_KEY>
                    appKey: <APP_KEY>
                    token: 
                  clusterName: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "default" "cluster").status.infrastructureName }}'    
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-datadog-operator
  namespace: acm-policy
placementRef:
  name: placement-policy-datadog-operator
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-datadog-operator
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-datadog-operator
  namespace: acm-policy
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: jfn
        operator: In
        values:
          - 'yes'
