apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: openshift-operators
spec:
  agent:
    config:
      criSocket:
        criSocketPath: /var/run/crio/crio.sock
      kubelet:
        tlsVerify: false
      securityContext:
        runAsUser: 0
        seLinuxOptions:
          level: s0
          role: system_r
          type: spc_t
          user: system_u
    rbac:
      serviceAccountName: datadog-agent-scc
    apm:
      enabled: false
    log:
      enabled: false
      logsConfigContainerCollectAll: false
    process:
      enabled: true
      processCollection: false
    security:
      compliance:
        enabled: false
      runtime:
        enabled: false
    systemProbe:
      bpfDebugEnabled: false
  clusterAgent:
    config:
      admissionController:
        enabled: false
      externalMetrics:
        enabled: false
      clusterChecksEnabled: false
    replicas: 2
  clusterChecksRunner:
    replicas: 2
  credentials:
    apiKey: <API_KEY>
    appKey: <APP_KEY>
    token: 
  clusterName: <CLUSTER_NAME>
