apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-datadog-operator
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: datadog-operator-namespace
        spec:
          remediationAction: enforce 
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-datadog

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: datadog-operator-operator-group
        spec:
          remediationAction: enforce 
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: datadog-operator
                  namespace: openshift-operator
                spec:
                  targetNamespaces:
                    - openshift-operator

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: datadog-operator-subscription
        spec:
          remediationAction:   
          severity: high
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["*"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alphz
                kind: Subscription
                metadata:
                  name: datadog-operator
                  namespace: openshift-operator
                spec:
                  channel: "4.7"
                  installPlanApproval: Automatic
                  name: datadog-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace

---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: datadog-operator-binding
placementRef:
  name: datadog-operator-placementrule
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-datadog-operator
  kind: Policy
  apiGroup: policy.open-cluster-management.io

---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: datadog-operator-placementrule
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: compliance-operator, operator: In, values: ["dontknow"]}
      